In [3]:
import torch
a = torch.tensor([1,2,3,4,5])
b = a[0:1]

In [4]:
b

tensor([1])

In [5]:
shifted = torch.cat((b, a), 0)
shifted = shifted[:-1]
res = torch.cat((a, (a - b)), -1)

In [6]:
shifted

tensor([1, 1, 2, 3, 4])

In [7]:
a-b

tensor([0, 1, 2, 3, 4])

In [8]:
res

tensor([1, 2, 3, 4, 5, 0, 1, 2, 3, 4])

In [9]:
i = torch.tensor([1,2,3,4,5])

In [10]:
feature = i

t1 = i[0:1]
shifted = torch.cat((t1, i), -1)
shifted = shifted[:-1]
delta = i - shifted

shifted_1 = torch.cat((t1,t1, i), -1)
shifted_1 = shifted_1[:-2]
delta_2 = shifted - shifted_1

res = torch.cat((i, delta, delta_2), -1)

In [11]:
res

tensor([1, 2, 3, 4, 5, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1])

In [12]:
print

<function print>

In [29]:
import torch.tensor
from sklearn.linear_model import LinearRegression
import numpy as np
import pandas as pd

In [45]:
res = res.reshape(3,5)

In [46]:
a = res.numpy()
type(a)

numpy.ndarray

In [48]:
a

array([[1, 2, 3, 4, 5],
       [0, 1, 1, 1, 1],
       [0, 0, 1, 1, 1]])