In [6]:
import torch
a = torch.tensor([1,2,3,4,5])
b = a[0:1]

In [14]:
b

tensor([1])

In [12]:
shifted = torch.cat((b, a), 0)
shifted = shifted[:-1]
res = torch.cat((a, (a - b)), -1)

In [15]:
shifted

tensor([1, 1, 2, 3, 4])

In [16]:
a-b

tensor([0, 1, 2, 3, 4])

In [17]:
res

tensor([1, 2, 3, 4, 5, 0, 1, 2, 3, 4])

In [18]:
i = torch.tensor([1,2,3,4,5])

In [23]:
feature = i

t1 = i[0:1]
shifted = torch.cat((t1, i), -1)
shifted = shifted[:-1]
delta = i - shifted

shifted_1 = torch.cat((t1,t1, i), -1)
shifted_1 = shifted_1[:-2]
delta_2 = shifted - shifted_1

res = torch.cat((i, delta, delta_2), -1)

In [24]:
res

tensor([1, 2, 3, 4, 5, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1])